services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_LOGIN_ACCOUNT: ${NEXT_PUBLIC_LOGIN_ACCOUNT}
        NEXT_PUBLIC_LOGIN_PASSWORD: ${NEXT_PUBLIC_LOGIN_PASSWORD}
        NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE: ${NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE:-true}
        NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY: ${NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY}
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
        NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL: ${NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL}
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_LOGIN_ACCOUNT: ${NEXT_PUBLIC_LOGIN_ACCOUNT}
      NEXT_PUBLIC_LOGIN_PASSWORD: ${NEXT_PUBLIC_LOGIN_PASSWORD}
      NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE: ${NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE:-true}
      CONFIG_STORAGE_FILE: ${CONFIG_STORAGE_FILE:-/app/data/config-store.json}
      NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY: ${NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY}
      NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
      NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL: ${NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL}
    volumes:
      - config_data:/app/data

volumes:
  config_data:
