# ===== 构建阶段（Alpine 减小体积）=====
# 未传入的 build-arg 使用占位符，便于运行阶段用环境变量替换
FROM node:22-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_LOGIN_ACCOUNT=__NEXT_PUBLIC_LOGIN_ACCOUNT__
ARG NEXT_PUBLIC_LOGIN_PASSWORD=__NEXT_PUBLIC_LOGIN_PASSWORD__
ARG NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE=__NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE__
ARG NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY=__NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY__
ARG NEXT_PUBLIC_GA_ID=__NEXT_PUBLIC_GA_ID__
ARG NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL=__NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL__
ENV NEXT_PUBLIC_LOGIN_ACCOUNT=$NEXT_PUBLIC_LOGIN_ACCOUNT
ENV NEXT_PUBLIC_LOGIN_PASSWORD=$NEXT_PUBLIC_LOGIN_PASSWORD
ENV NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE=$NEXT_PUBLIC_ENABLE_SERVER_FILE_STORAGE
ENV NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY=$NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL=$NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npx next build

# ===== 运行阶段（静态资源 + 文件配置服务）=====
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/out ./out
COPY server.js entrypoint.sh ./
RUN chmod +x /app/entrypoint.sh && mkdir -p /app/data

EXPOSE 3000
VOLUME ["/app/data"]
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/healthz').then((res) => process.exit(res.ok ? 0 : 1)).catch(() => process.exit(1))"
ENTRYPOINT ["/app/entrypoint.sh"]
