-- 当前版本不再依赖 Supabase Auth。
-- user_id 由前端根据登录账号生成稳定 UUID，用来区分不同账号的数据。

-- 建表
create table public.user_configs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  data json null,
  updated_at text null,
  user_id uuid not null,
  constraint user_configs_pkey primary key (id),
  constraint user_configs_user_id_key unique (user_id)
) TABLESPACE pg_default;

-- 启用行级安全（RLS）
alter table public.user_configs enable row level security;

drop policy if exists "user_configs_select_own" on public.user_configs;
drop policy if exists "user_configs_insert_own" on public.user_configs;
drop policy if exists "user_configs_update_own" on public.user_configs;

create policy "user_configs_select_own"
on public.user_configs
for select
to anon, authenticated
using (true);

create policy "user_configs_insert_own"
on public.user_configs
for insert
to anon, authenticated
with check (true);

create policy "user_configs_update_own"
on public.user_configs
for update
to anon, authenticated
using (true)
with check (true);

grant select, insert, update on table public.user_configs to anon;
grant select, insert, update on table public.user_configs to authenticated;
grant usage, select on sequence public.user_configs_id_seq to anon;
grant usage, select on sequence public.user_configs_id_seq to authenticated;

-- 增量更新函数
create or replace function public.update_user_config_partial(target_user_id uuid, payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as
$$
begin
update public.user_configs
set data = ((coalesce(data::jsonb, '{}'::jsonb) || payload)::json),
    updated_at = now()
where user_id = target_user_id;
end;
$$;

grant execute on function public.update_user_config_partial(uuid, jsonb) to anon;
grant execute on function public.update_user_config_partial(uuid, jsonb) to authenticated;
grant execute on function public.update_user_config_partial(uuid, jsonb) to service_role;
